name: CI-CD-Pipeline-to-AWS
env:
  S3_BUCKET_NAME     : "alpacked-test-assignment"
  DEPLOY_PACKAGE_NAME: "web_site_${{ github.sha }}.zip"
  AWS_REGION_NAME    : "eu-central-1"
  
on:
  push:
    branches: 
    - main

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
        
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Build
        run: |
          yarn install && yarn build
        
      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
          
      - name: Copy deployment packege to S3
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/
        
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: ${{ secrets.S3_BUCKET_NAME }}
